version: '2.4'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
    environment:
      - GID_POSTGRESQL_USER=root
      - GID_POSTGRESQL_PASSWORD=secret

  postgresql:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=GID
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgresql-data:/var/lib/postgresql/data
volumes:
  postgresql-data: