// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
)

type ImageResult struct {
	ID        int64          `json:"id"`
	QueryID   int64          `json:"query_id"`
	ImageUrl  sql.NullString `json:"image_url"`
	ImageData sql.NullString `json:"image_data"`
	Timestamp sql.NullTime   `json:"timestamp"`
}

type Query struct {
	ID        int64        `json:"id"`
	Query     string       `json:"query"`
	Status    string       `json:"status"`
	PerPage   int32        `json:"per_page"`
	Page      int32        `json:"page"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
